services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  machine-learning-client:
    build: ./machine-learning-client
    container_name: machine-learning-client
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - DB_NAME=crimson_viper
    volumes:
      - audio_data:/data/audio

  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - DB_NAME=crimson_viper
      - SECRET_KEY=secret-key
    volumes:
      - audio_data:/data/audio

volumes:
  audio_data:
  mongo_data:
